--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Laith98Dev/NoPVP
build-by-default: true
branches:
- main
projects:
    NoPVP:
        path: ""
        icon: 20210908_194345.jpg
        libs:
            - src: jojoe77777/FormAPI/libFormAPI
              version: ^1.3
...
